"""Persist Builder text layers as real artwork files for products and orders.

Builder V2 renders editable text as SVG data URLs in the browser. Those data URLs
are useful while editing, but printers need stable file URLs in the same production
snapshot used for uploaded images. This patch materialises generated SVG text layers
under backend/uploads/product-artwork/text during product normalisation and preserves
the editable text metadata in order production snapshots.
"""
from __future__ import annotations

import base64
import binascii
import hashlib
import re
from copy import deepcopy
from pathlib import Path
from typing import Any
from urllib.parse import unquote_to_bytes

from fastapi import HTTPException

from storage import UPLOAD_ROOT


_TEXT_UPLOAD_DIR = Path(UPLOAD_ROOT) / "product-artwork" / "text"
_TEXT_PUBLIC_PREFIX = "/api/uploads/product-artwork/text"
_DATA_URL_RE = re.compile(
    r"^data:(?P<mime>[^;,]+)?(?P<charset>;charset=[^;,]+)?(?P<base64>;base64)?,(?P<data>.*)$",
    re.IGNORECASE | re.DOTALL,
)
_TEXT_METADATA_FIELDS = (
    "text_layer",
    "text_content",
    "text_font_family",
    "text_font_weight",
    "text_font_size",
    "text_color",
    "lock_aspect_ratio",
    "original_width_px",
    "original_height_px",
    "artwork_aspect_ratio",
    "generated_artwork_file",
    "artwork_source_type",
    "artwork_content_sha256",
)


def _is_text_layer(slot: dict | None) -> bool:
    slot = slot or {}
    return bool(slot.get("text_layer") or slot.get("text_content"))


def _decode_svg_data_url(value: str) -> bytes:
    match = _DATA_URL_RE.match(str(value or ""))
    if not match:
        raise HTTPException(status_code=400, detail="Generated text artwork is not a valid data URL")

    mime_type = str(match.group("mime") or "image/svg+xml").lower()
    if mime_type != "image/svg+xml":
        raise HTTPException(status_code=400, detail="Generated text artwork must be SVG")

    payload = match.group("data") or ""
    try:
        content = base64.b64decode(payload, validate=True) if match.group("base64") else unquote_to_bytes(payload)
    except (ValueError, binascii.Error) as exc:
        raise HTTPException(status_code=400, detail="Generated text artwork could not be decoded") from exc

    if len(content) < 20 or b"<svg" not in content.lower():
        raise HTTPException(status_code=400, detail="Generated text artwork does not contain a valid SVG document")

    # Text SVGs are generated by Builder V2. Reject executable constructs if a
    # crafted API request attempts to bypass the browser generator.
    lowered = content.lower()
    forbidden = (b"<script", b"javascript:", b"onload=", b"onerror=", b"<foreignobject")
    if any(token in lowered for token in forbidden):
        raise HTTPException(status_code=400, detail="Generated text artwork contains unsupported SVG content")

    return content


def _materialize_text_slot(slot: dict | None) -> dict:
    next_slot = dict(slot or {})
    if not _is_text_layer(next_slot):
        return next_slot

    original_url = str(next_slot.get("original_url") or "")
    if original_url and not original_url.startswith("data:"):
        next_slot.setdefault("generated_artwork_file", True)
        next_slot.setdefault("artwork_source_type", "generated_text_svg")
        return next_slot

    if not original_url:
        return next_slot

    content = _decode_svg_data_url(original_url)
    digest = hashlib.sha256(content).hexdigest()
    _TEXT_UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

    # Content-addressed names make repeated saves idempotent: unchanged text reuses
    # the same production file, while an actual text/font/colour change creates a
    # new immutable artwork asset.
    file_name = f"{digest}.svg"
    destination = _TEXT_UPLOAD_DIR / file_name
    if not destination.exists():
        destination.write_bytes(content)

    next_slot.update(
        {
            "original_url": f"{_TEXT_PUBLIC_PREFIX}/{file_name}",
            "file_name": next_slot.get("file_name") or "text-layer.svg",
            "mime_type": "image/svg+xml",
            "generated_artwork_file": True,
            "artwork_source_type": "generated_text_svg",
            "artwork_content_sha256": digest,
        }
    )
    return next_slot


def _materialize_product_artworks(product: dict | None) -> dict:
    prepared = deepcopy(product or {})

    prepared["artworks"] = [
        _materialize_text_slot(slot)
        for slot in (prepared.get("artworks") or [])
    ]

    groups = []
    for group in prepared.get("artwork_groups") or []:
        next_group = dict(group or {})
        next_group["artworks"] = [
            _materialize_text_slot(slot)
            for slot in (next_group.get("artworks") or [])
        ]
        groups.append(next_group)
    prepared["artwork_groups"] = groups

    by_id = {
        slot.get("id"): slot
        for group in groups
        for slot in (group.get("artworks") or [])
        if slot.get("id")
    }
    if by_id:
        prepared["artworks"] = [
            dict(by_id.get(slot.get("id")) or slot)
            for slot in prepared.get("artworks") or []
        ]

    primary = prepared.get("artwork") or {}
    if _is_text_layer(primary):
        prepared["artwork"] = _materialize_text_slot(primary)

    return prepared


def _source_artwork_rows(product: dict) -> list[dict]:
    rows: list[dict] = []
    for group in product.get("artwork_groups") or []:
        rows.extend(group.get("artworks") or [])
    rows.extend(product.get("artworks") or [])
    return [dict(row or {}) for row in rows]


def _copy_text_metadata(target: dict | None, source: dict | None) -> None:
    if not target or not source or not _is_text_layer(source):
        return
    for key in _TEXT_METADATA_FIELDS:
        if key in source:
            target[key] = source.get(key)
    target["url"] = source.get("original_url") or target.get("url")
    target["file_name"] = source.get("file_name") or target.get("file_name")
    target["mime_type"] = source.get("mime_type") or target.get("mime_type") or "image/svg+xml"


def install_builder_text_artwork_patch(routes_main_module: Any) -> None:
    """Install text-file persistence after the existing Builder artwork patches."""
    if getattr(routes_main_module, "_builder_text_artwork_patch_installed", False):
        return

    original_normalize_slot = routes_main_module._normalize_product_artwork_slot
    original_build_snapshot = routes_main_module._build_production_snapshot

    def patched_normalize_slot(row: dict, index: int = 0) -> dict:
        slot = original_normalize_slot(row, index)
        return _materialize_text_slot(slot)

    def patched_build_snapshot(product: dict, template: dict | None, product_variation: dict | None, quantity: int) -> dict:
        prepared_product = _materialize_product_artworks(product)
        snapshot = original_build_snapshot(prepared_product, template, product_variation, quantity)

        source_rows = _source_artwork_rows(prepared_product)
        by_id = {row.get("id"): row for row in source_rows if row.get("id")}
        by_url = {row.get("original_url"): row for row in source_rows if row.get("original_url")}

        for target in snapshot.get("artworks") or []:
            source = by_id.get(target.get("id")) or by_url.get(target.get("url"))
            _copy_text_metadata(target, source)

        primary_target = snapshot.get("artwork") or {}
        primary_source = by_id.get(primary_target.get("id")) or by_url.get(primary_target.get("url"))
        _copy_text_metadata(primary_target, primary_source)
        snapshot["artwork"] = primary_target
        return snapshot

    routes_main_module._normalize_product_artwork_slot = patched_normalize_slot
    routes_main_module._build_production_snapshot = patched_build_snapshot
    routes_main_module._builder_text_artwork_patch_installed = True
