from pathlib import Path

p = Path('frontend/src/components/admin/creators/AdminCreatorsWorkspace.jsx')
text = p.read_text()

def replace_once(old, new, label):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 match, found {count}')
    text = text.replace(old, new, 1)

replace_once('import { NavLink, Navigate, Route, Routes, useNavigate } from "react-router-dom";', 'import { NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";', 'router import')
replace_once('function BandsAdmin() {\n  const [rows, setRows] = useState([]);', 'function BandsAdmin({ view = "list", creatorId = null, basePath = "/admin" }) {\n  const navigate = useNavigate();\n  const [rows, setRows] = useState([]);', 'BandsAdmin signature')
replace_once('  const reset = () => {\n    setEditingId(null);\n    setForm(emptyCreatorForm);\n  };\n', '  const reset = () => {\n    setEditingId(null);\n    setForm(emptyCreatorForm);\n  };\n\n  const goToList = () => navigate(`${basePath}/creators/accounts`);\n', 'reset block')
replace_once('  const payload = () => ({', '  useEffect(() => {\n    if (view !== "edit" || !creatorId || !rows.length) return;\n    const row = rows.find((item) => String(item.id) === String(creatorId));\n    if (row) edit(row);\n  }, [creatorId, rows, view]);\n\n  const payload = () => ({', 'edit preload effect')
replace_once('      if (editingId) {\n        await http.patch(`/admin/creators/${editingId}`, payload());', '      if (view === "edit" && creatorId) {\n        await http.patch(`/admin/creators/${creatorId}`, payload());', 'save edit condition')
replace_once('      reset();\n      await load();', '      reset();\n      goToList();', 'save navigation')
replace_once('''      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">\n        <div>\n          <div className="overline mb-2">Account Management</div>\n          <h1 className="font-display text-5xl uppercase">Creators</h1>\n          <p className="text-[var(--ff-muted-text)] mt-2 max-w-3xl">Create, edit and manage top-level creator storefront accounts, profile images, banners and user ownership.</p>\n        </div>\n        <button type="button" onClick={reset} className="btn-secondary"><Plus size={14} /> New Creator</button>\n      </div>\n\n      <form onSubmit={save} className="card grid lg:grid-cols-3 gap-4">''', '''      {view === "list" ? (\n        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">\n          <div>\n            <div className="overline mb-2">Account Management</div>\n            <h1 className="font-display text-5xl uppercase">Creators</h1>\n            <p className="text-[var(--ff-muted-text)] mt-2 max-w-3xl">Manage creator storefront accounts. Open a creator to edit its profile, publishing, billing and ownership settings.</p>\n          </div>\n          <button type="button" onClick={() => navigate(`${basePath}/creators/accounts/new`)} className="btn-primary"><Plus size={14} /> New Creator</button>\n        </div>\n      ) : (\n        <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">\n          <div>\n            <button type="button" onClick={goToList} className="text-xs uppercase tracking-widest text-[var(--ff-muted-text)] hover:text-[var(--ff-card-text)] font-bold mb-4">← Back to Creators</button>\n            <div className="overline mb-2">Creator Account</div>\n            <h1 className="font-display text-5xl uppercase">{view === "edit" ? (form.name || "Edit Creator") : "New Creator"}</h1>\n            <p className="text-[var(--ff-muted-text)] mt-2 max-w-3xl">{view === "edit" ? "Update this creator account and storefront settings." : "Create a new top-level creator storefront account."}</p>\n          </div>\n        </div>\n      )}\n\n      {view !== "list" && (\n      <form onSubmit={save} className="card grid lg:grid-cols-3 gap-4">''', 'header and form opening')
replace_once('          <div className="overline mb-2">{editingId ? "Edit Creator" : "Create Creator"}</div>\n          <h2 className="font-display text-3xl uppercase">{editingId ? form.name || "Edit account" : "New creator account"}</h2>', '          <div className="overline mb-2">{view === "edit" ? "Edit Creator" : "Create Creator"}</div>\n          <h2 className="font-display text-3xl uppercase">{view === "edit" ? form.name || "Edit account" : "New creator account"}</h2>', 'form heading')
replace_once('          <button type="submit" className="btn-primary" disabled={saving}><Save size={14} /> {saving ? "Saving…" : editingId ? "Update Creator" : "Create Creator"}</button>\n          {editingId && <button type="button" onClick={reset} className="btn-secondary">Cancel edit</button>}', '          <button type="submit" className="btn-primary" disabled={saving}><Save size={14} /> {saving ? "Saving…" : view === "edit" ? "Update Creator" : "Create Creator"}</button>\n          <button type="button" onClick={goToList} className="btn-secondary">Cancel</button>', 'form buttons')
replace_once('      </form>\n\n      <div className="border border-[var(--ff-card-border)] overflow-x-auto">', '      </form>\n      )}\n\n      {view === "list" && (\n      <div className="border border-[var(--ff-card-border)] overflow-x-auto">', 'form close/list open')
replace_once('                <td className="text-right whitespace-nowrap"><button type="button" onClick={() => edit(b)} className="text-xs uppercase tracking-widest text-[var(--ff-primary)] font-bold mr-4">Edit</button><button type="button" onClick={() => remove(b)} className="text-xs uppercase tracking-widest text-[var(--ff-muted-text)] hover:text-[var(--ff-primary)] font-bold">Delete</button></td>', '                <td className="text-right whitespace-nowrap"><button type="button" onClick={() => navigate(`${basePath}/creators/accounts/${b.id}`)} className="text-xs uppercase tracking-widest text-[var(--ff-primary)] font-bold mr-4">Edit</button><button type="button" onClick={() => remove(b)} className="text-xs uppercase tracking-widest text-[var(--ff-muted-text)] hover:text-[var(--ff-primary)] font-bold">Delete</button></td>', 'edit action')
replace_once('      </div>\n    </div>\n  );\n}\n\nfunction ProductsAdmin()', '      </div>\n      )}\n    </div>\n  );\n}\n\nfunction CreatorAccountEditRoute({ basePath = "/admin" }) {\n  const { id } = useParams();\n  return <BandsAdmin view="edit" creatorId={id} basePath={basePath} />;\n}\n\nfunction ProductsAdmin()', 'list close/wrapper')
replace_once('{canAccounts && <Route path="accounts" element={<BandsAdmin />} />}', '{canAccounts && <Route path="accounts" element={<BandsAdmin view="list" basePath={basePath} />} />}\n        {canAccounts && <Route path="accounts/new" element={<BandsAdmin view="new" basePath={basePath} />} />}\n        {canAccounts && <Route path="accounts/:id" element={<CreatorAccountEditRoute basePath={basePath} />} />}', 'account routes')
p.write_text(text)
